import cloudbase from "@cloudbase/js-sdk";

// 初始化 CloudBase 应用（密钥已完整配置，无换行、无空格）
const app = cloudbase.init({
  env: "jingtailan-d7gcv0lzd06bf0240",
  region: "ap-shanghai",
  accessKey: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjlkMWRjMzFlLWI0ZDAtNDQ4Yi1hNzZmLWIwY2M2M2Q4MTQ5OCJ9.eyJpc3MiOiJodHRwczovL2ppbmd0YWlsYW4tZDdnY3YwbHpkMDZiZjAyNDAuYXAtc2hhbmdoYWkudGNiLWFwaS50ZW5jZW50Y2xvdWRhcGkuY29tIiwic3ViIjoiYW5vbiIsImF1ZCI6Imppbmd0YWlsYW4tZDdnY3YwbHpkMDZiZjAyNDAiLCJleHAiOjQwODQzMjE3NzUsImlhdCI6MTc4MDYzODU3NSwibm9uY2UiOiJBSnhkeUowR1RTNkY4OGdhdEJrN3R3IiwiYXRfaGFzaCI6IkFKeGR5SjBHVFM2Rjg4Z2F0Qms3dHciLCJuYW1lIjoiQW5vbnltb3VzIiwic2NvcGUiOiJhbm9ueW1vdXMiLCJwcm9qZWN0X2lkIjoiamluZ3RhaWxhbi1kN2djdjBsemQwNmJmMDI0MCIsIm1ldGEiOnsicGxhdGZvcm0iOiJQdWJsaXNoYWJsZUtleSJ9LCJ1c2VyX3R5cGUiOiIiLCJjbGllbnRfdHlwZSI6ImNsaWVudF91c2VyIiwiaXNfc3lzdGVtX2FkbWluIjpmYWxzZX0.RxV4DxINO2Bb3JA5qjZ_A0N5kxiFmvH-RklfGavSsFGbFw0BTjxs6Ls1IApRWs6mqYAdKsPxGBWnBvtTLUfoF7_E_kqF57B6n9Ae5gWPB5YWk8cnf1UovsGpm8WkblkXy6EpjZWZlivhbfg-wfBTKp96OymUVzNk6LusCPo0bUsRngcEXcMnJgfOe2vWnc8YkTdxq57ZFB7XJ1Rsvztzhd5NFKaeup0h9H-hMxhSemnlAO0Fjpl9oynlHPbIsO_UQoNZd1G0geNEFElojkE3rj7zdHP2novmECQrZKHdnhWGQiD9VmuZr78usBsOivFo_SKHe2Wcdsy5scj_HHurmg",
  auth: { detectSessionInUrl: true }  // 必须配置，用于检测 URL 中的会话信息
});

// 导出认证和数据库实例供其他组件使用
export const auth = app.auth();
export const db = app.database();